import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Barlow_Semi_Condensed } from "next/font/google";
import Rules from "@/components/Rules";

const barlow = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["600", "700"],
});

export const metadata: Metadata = {
  title: "Rock, Paper, Scissors, Lizard, Spock",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${barlow.className} min-h-screen flex flex-col items-center bg-gradient-radial from-background-center to-background-edge bg-size-350 bg-top`}
      >
        <Header />
        <main className="flex items-center justify-center flex-1">
          {children}
        </main>
        <Rules />
      </body>
    </html>
  );
}
